Vagrant.configure("2") do |config|

   config.vm.box = "debian/buster64"
 
 
   config.vm.define "git_server" do |git_server|
     git_server.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
     end
 
     git_server.vm.network "private_network", ip: "192.168.33.13"
     git_server.vm.hostname = 'git-server'
 
     git_server.vm.provision "shell", inline: <<-SHELL
       echo "Adding SSH Key"
       echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/m/0XNTR0SiULKecyEbfuu2mXsVHVrr6GmjhAhHBc5TS4PYGmVmPPoDoq54b+J9BtxY45FhKR5gbexmPU/7h+ZLjgbzMic4Sikdmg0Sd3eiLtGoQT6v780MUy1DN+POdgIrWX9pfOtJxlo4aTlqvtiAn4xQY7prxHiTmc6cjXYiHl721+KmuGRxz07HPrXGh9+3kMNA3sDeVeC5TDao7D9lA8YUTfyWerwRtKXDCCY1DJHU1RirnNT03l1oGEqQyZP+tdhJd2h7IBgtRuM1R4cNUKwAUpyCuEEvVu/zNMsVObZgojEL/zJd3pSf3RpNr/R8+dRM3ov3SffuJF4tWHVC9JBc6eb0kA2jcv28d9DBX4FavCzm0RQiT4H6lEp7CsTYUho0winc7AnKI3fcJp+vTKJkvA51FaYCGJiSWi7jBYUo9L8ryDACtuKXS80xIqsSXF9U9ExZRUHLy5Ei6r0pEJrx+pEw2oAYtXe60LeoY0Gygkdh8b+0UEJBv7kYU=' >> /home/vagrant/.ssh/authorized_keys
     SHELL
   end
 
 end